In [2]:
import pandas as pd

df = pd.read_csv("../PLN/data/noticias_games (2).csv")
df.head()

,url,titulo,descricao,autor,tags,texto,data
0,https://www.eurogamer.pt/tecmo-bowl-sera-adapt...,Tecmo Bowl será adaptado para filme,"Tecmo Bowl, clássico da Koei Tecmo lançado no ...",NaN,"Android, iOS","Tecmo Bowl, clássico da Koei Tecmo lançado no ...",2026-02-03T16:35:31.309576+00:00
1,https://www.eurogamer.pt/fas-adoram-super-mari...,Fãs adoram Super Mario Galaxy: O Filme,Super Mario Galaxy: O Filme chegou finalmente ...,NaN,"Action Adventure, Platformer, Nintendo Switch,...",Super Mario Galaxy: O Filme chegou finalmente ...,2026-04-02T07:40:11.552201+00:00
2,https://www.eurogamer.pt/pokemon-firered-leafg...,Pokémon FireRed & LeafGreen inclui conteúdo au...,Pokémon FireRed & LeafGreen para a Nintendo Sw...,NaN,"Action Adventure, Pokémon FireRed and LeafGree...",Pokémon FireRed & LeafGreen para a Nintendo Sw...,2026-03-01T09:15:15.110566+00:00
3,https://www.eurogamer.pt/switch-2-ja-alcancou-...,Switch 2 já alcançou 58% das vendas da PS5 em ...,"O recente relatório do governo japonês, sobre ...",NaN,"Third person, Racing, Nintendo, Nintendo Switc...","O recente relatório do governo japonês, sobre ...",2026-02-09T13:33:14.368225+00:00
4,https://www.eurogamer.pt/produtora-de-slay-the...,Produtora de Slay the Spire 2 detesta micro-tr...,"Slay the Spire 2 chegou com grande sucesso, em...",NaN,"Multiplayer Cooperative, Indie, PC, Slay the S...","Slay the Spire 2 chegou com grande sucesso, em...",2026-03-10T14:42:15.059919+00:00

In [4]:
from nltk.tokenize import wordpunct_tokenize
from unidecode import unidecode


def limpar_texto(texto):
    texto = texto.lower()
    texto = unidecode(texto)
    tokens = wordpunct_tokenize(texto)
    tokens = [token for token in tokens if token.isalnum()]
    return " ".join(tokens)


df["texto_limpo"] = df["texto"].apply(limpar_texto)

df[["texto", "texto_limpo"]].head()

,texto,texto_limpo
0,"Tecmo Bowl, clássico da Koei Tecmo lançado no ...",tecmo bowl classico da koei tecmo lancado no f...
1,Super Mario Galaxy: O Filme chegou finalmente ...,super mario galaxy o filme chegou finalmente a...
2,Pokémon FireRed & LeafGreen para a Nintendo Sw...,pokemon firered leafgreen para a nintendo swit...
3,"O recente relatório do governo japonês, sobre ...",o recente relatorio do governo japones sobre o...
4,"Slay the Spire 2 chegou com grande sucesso, em...",slay the spire 2 chegou com grande sucesso em ...

In [5]:
import nltk

from nltk.corpus import stopwords


nltk.download("stopwords", quiet=True)

stopwords_pt = stopwords.words("portuguese")
stopwords_pt = [unidecode(palavra) for palavra in stopwords_pt]
stopwords_pt = set(stopwords_pt)


def remover_stopwords(texto):
    tokens = texto.split()
    tokens = [token for token in tokens if token not in stopwords_pt]
    return tokens


df["tokens_sem_stopwords"] = df["texto_limpo"].apply(remover_stopwords)
df["texto_sem_stopwords"] = df["tokens_sem_stopwords"].str.join(" ")

df[["texto_limpo", "tokens_sem_stopwords", "texto_sem_stopwords"]].head()

,texto_limpo,tokens_sem_stopwords,texto_sem_stopwords
0,tecmo bowl classico da koei tecmo lancado no f...,"[tecmo, bowl, classico, koei, tecmo, lancado, ...",tecmo bowl classico koei tecmo lancado final a...
1,super mario galaxy o filme chegou finalmente a...,"[super, mario, galaxy, filme, chegou, finalmen...",super mario galaxy filme chegou finalmente cin...
2,pokemon firered leafgreen para a nintendo swit...,"[pokemon, firered, leafgreen, nintendo, switch...",pokemon firered leafgreen nintendo switch incl...
3,o recente relatorio do governo japones sobre o...,"[recente, relatorio, governo, japones, sobre, ...",recente relatorio governo japones sobre gastos...
4,slay the spire 2 chegou com grande sucesso em ...,"[slay, the, spire, 2, chegou, grande, sucesso,...",slay the spire 2 chegou grande sucesso acesso ...

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
matriz_bow = vectorizer.fit_transform(df["texto_sem_stopwords"])

df_bow = pd.DataFrame(
    matriz_bow.toarray(),
    columns=vectorizer.get_feature_names_out()
)

df_bow.head()

AttributeError: module 'numpy._core._multiarray_umath' has no attribute '_blas_supports_fpe'